# Generated by Django 3.0.5 on 2021-08-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_registrations', '0005_auto_20210802_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
